//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.comments = new HashSet<comment>();
            this.FriendRequests = new HashSet<FriendRequest>();
            this.FriendRequests1 = new HashSet<FriendRequest>();
            this.likes = new HashSet<like>();
            this.posts = new HashSet<post>();
        }
    
        public int UserID { get; set; }
        public string ImageTitle { get; set; }
        [DisplayName("Upload Picture")]
        public string ImagePath { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage ="You have to enter your first name")]
        public string Fname { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "You have to enter your last name")]
        public string Lname { get; set; }
        [DisplayName("Email Name")]
        [Required(ErrorMessage = "You have to enter your email")]
        public string email { get; set; }
        [DisplayName(" Mobile")]
        [Required(ErrorMessage = "You have to enter your mobile")]
        public string mobile { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "You have to enter your password")]
        public string Password { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequest> FriendRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequest> FriendRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> posts { get; set; }
    }
}
