//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Collections.Generic;
    using Instagram.Globals;
    
    public partial class comment
    {
        public int CommentID { get; set; }
        public string data { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
        public comment newComment(comment comment)
        {
            comment newComment = new comment {
                PostID = comment.PostID,
                UserID = GlobalUserID.get(),
                data=comment.data
            };
            return newComment;
        }
    }
}
