//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int RequestID { get; set; }
        public int SenderID { get; set; }
        public int RecieverID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
