//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Collections.Generic;
    using Instagram.Globals;
    
    public partial class like
    {
        public int LikeID { get; set; }
        public int UserID { get; set; }
        public int PostID { get; set; }
        public Nullable<bool> NuLikes { get; set; }
        public Nullable<bool> NuDislikes { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
        public like Like(int id)
        {
            like newLike = new like
            {
                PostID = id,
                NuLikes = true,
                NuDislikes = false,
                UserID = GlobalUserID.get()
            };
            return newLike;
        }
        public like disLike(int id)
        {
            like newDislike = new like {
                PostID = id,
                NuLikes = false,
                NuDislikes = true,
                UserID = GlobalUserID.get()
            };
            return newDislike;
        }
    }

    }
