//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramFinall.Models
{
    using System;
    using System.Collections.Generic;
    using InstagramFinall.Globals;

    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Data { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public Comment NewComment(Comment Comment)
        {
            Comment NewComment = new Comment
            {
                PostId = Comment.PostId,
                UserId = GlobalUserId.Get(),
                Data = Comment.Data
            };
            return NewComment;
        }
    }
}
