//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramFinall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int RequestId { get; set; }
        public int SenderId { get; set; }
        public int RecieverId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
