//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramFinall.Models
{
    using System;
    using System.Collections.Generic;
    using InstagramFinall.Globals;
    public partial class Like
    {
        public int LikeId { get; set; }
        public int UserId { get; set; }
        public int PostId { get; set; }
        public Nullable<bool> NuLikes { get; set; }
        public Nullable<bool> NuDislikes { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public Like CreateLike(int id)
        {
            Like NewLike = new Like
            {
                PostId = id,
                NuLikes = true,
                NuDislikes = false,
                UserId = GlobalUserId.Get()
            };
            return NewLike;
        }
        public Like DisLike(int id)
        {
            Like NewDislike = new Like
            {
                PostId = id,
                NuLikes = false,
                NuDislikes = true,
                UserId = GlobalUserId.Get()
            };
            return NewDislike;
        }
    }
}
